"""Regression tests for dependency-free statistical primitives."""

import math
import unittest

import numpy as np

from ier._statistics import (
    chi_square_quantile,
    chi_square_quantiles,
    normal_pdf,
    normal_quantile,
)


class TestNormalDistribution(unittest.TestCase):
    def test_quantiles_match_reference_values(self) -> None:
        probabilities = [0.025, 0.5, 0.975]
        expected = [-1.959963984540054, 0.0, 1.959963984540054]
        actual = [normal_quantile(probability) for probability in probabilities]
        np.testing.assert_allclose(actual, expected, rtol=1e-14, atol=1e-14)

    def test_quantile_boundaries_and_validation(self) -> None:
        self.assertEqual(normal_quantile(0.0), -math.inf)
        self.assertEqual(normal_quantile(1.0), math.inf)
        for invalid in (-0.1, 1.1, math.nan, math.inf):
            with self.subTest(invalid=invalid), self.assertRaises(ValueError):
                normal_quantile(invalid)

    def test_pdf_matches_reference_values_and_broadcasts(self) -> None:
        values = np.array([-1.0, 0.0, 1.0])
        actual = normal_pdf(values, loc=np.array([0.0, 0.0, 0.0]), scale=1.0)
        expected = [0.24197072451914337, 0.3989422804014327, 0.24197072451914337]
        np.testing.assert_allclose(actual, expected, rtol=1e-15)

        shifted = normal_pdf(np.array([1.0, 3.0]), loc=1.0, scale=np.array([1.0, 2.0]))
        np.testing.assert_allclose(shifted, [expected[1], expected[2] / 2.0], rtol=1e-15)

    def test_pdf_rejects_non_positive_scale(self) -> None:
        with self.assertRaises(ValueError):
            normal_pdf(np.array([0.0]), scale=0.0)


class TestChiSquareQuantile(unittest.TestCase):
    """Compare local quantiles with reference values generated by SciPy 1.16.3."""

    probabilities = np.array([1e-12, 1e-8, 1e-4, 0.01, 0.5, 0.95, 0.99, 1 - 1e-8, 1 - 1e-12])
    reference = {
        1: [
            1.5707963267948931e-24,
            1.5707963267948962e-16,
            1.5707963350195693e-8,
            0.00015708785790970184,
            0.454936423119572,
            3.8414588206941205,
            6.634896601021215,
            32.84125335146885,
            50.84417133244917,
        ],
        2: [
            2.000000000001e-12,
            2.0000000099999995e-8,
            0.0002000100006667168,
            0.020100671707002873,
            1.386294361119891,
            5.99146454710798,
            9.21034037197618,
            36.84136147785521,
            55.26208647578672,
        ],
        3: [
            2.41798794271803e-8,
            1.122333097304999e-5,
            0.005214832329027977,
            0.11483180189911707,
            2.3659738843753377,
            7.8147279032511765,
            11.34486673014437,
            40.129999007394105,
            58.9198006659047,
        ],
        10: [
            0.0207786897050036,
            0.13232794458438146,
            0.8889203579128959,
            2.5582121601872063,
            9.341817765591971,
            18.307038053275146,
            23.209251158954356,
            57.66396161460047,
            78.4716956802402,
        ],
        100: [
            30.084167586161836,
            39.71447235545694,
            55.724598450501624,
            70.06489492539978,
            99.33412923598846,
            124.34211340400408,
            135.80672317102676,
            200.63190871750663,
            233.81064336510852,
        ],
        1000: [
            716.9494787894976,
            768.9957227883816,
            842.1681465654505,
            898.9124469296132,
            999.333412403381,
            1074.679448803441,
            1106.9689943522174,
            1271.6322871248742,
            1347.6202217646367,
        ],
    }

    def test_matches_scipy_reference_grid(self) -> None:
        for degrees_of_freedom, expected in self.reference.items():
            with self.subTest(degrees_of_freedom=degrees_of_freedom):
                actual = chi_square_quantiles(self.probabilities, degrees_of_freedom)
                np.testing.assert_allclose(actual, expected, rtol=2e-12, atol=0.0)

    def test_scalar_and_vector_boundaries(self) -> None:
        self.assertEqual(chi_square_quantile(0.0, 3), 0.0)
        self.assertEqual(chi_square_quantile(1.0, 3), math.inf)
        actual = chi_square_quantiles(np.array([[0.5, 0.95]]), 5)
        self.assertEqual(actual.shape, (1, 2))
        np.testing.assert_allclose(actual, [[4.351460191095527, 11.070497693516351]])

    def test_quantiles_are_monotonic(self) -> None:
        probabilities = np.linspace(0.001, 0.999, 100)
        quantiles = chi_square_quantiles(probabilities, 7)
        self.assertTrue(np.all(np.diff(quantiles) > 0.0))

    def test_validation(self) -> None:
        with self.assertRaises(ValueError):
            chi_square_quantile(0.5, 0)
        for invalid in (-0.1, 1.1, math.nan, math.inf):
            with self.subTest(invalid=invalid), self.assertRaises(ValueError):
                chi_square_quantile(invalid, 3)


if __name__ == "__main__":
    unittest.main()
